Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,7 +19,7 @@ jobs:
       - name: 📦 Checkout code
         uses: actions/checkout@v3
 
-      - name: � Pods Set up Docker Buildx
+      - name: 🛠️ Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
       - name: 🔐 Login to Docker Hub
@@ -27,6 +27,11 @@ jobs:
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
+
+      - name: 🐞 Check DOCKER_USERNAME
+        run: |
+          echo "DOCKER_USERNAME is: ${{ env.DOCKER_USERNAME }}"
+          if [ -z "${{ env.DOCKER_USERNAME }}" ]; then echo "Error: DOCKER_USERNAME is empty"; exit 1; fi
 
       - name: 🧪 Prepare Backend tags
         id: backend_tags
@@ -47,8 +52,8 @@ jobs:
       - name: 🧪 Prepare Frontend tags
         id: frontend_tags
         run: |
-          echo "TAG_LATEST=${{ env.DOCKER_USERNAME }}/frontend:latest" >> $GITHUB_OUTPUT
-          echo "TAG_SHA=${{ env.DOCKER_USERNAME }}/frontend:${{ github.sha }}" >> $GITHUB_OUTPUT
+          echo "TAG_LATEST=${{ env.DOCKER_USERNAME }}/backend:latest" >> $GITHUB_OUTPUT
+          echo "TAG_SHA=${{ env.DOCKER_USERNAME }}/backend:${{ github.sha }}" >> $GITHUB_OUTPUT
 
       - name: 🧱 Build and push Frontend image
         uses: docker/build-push-action@v4
